{1: {'Title': 'Trample', 'Initiative': '72', 'Enhancements': {}},
 2: {'Title': 'Eye for an Eye', 'Initiative': '18', 'Enhancements': {}},
 3: {'Title': 'Sweeping Blow', 'Initiative': '64', 'Enhancements': {}},
 4: {'Title': 'Provoking Roar', 'Initiative': '10', 'Enhancements': {}},
 5: {'Title': 'Overwhelming Assault', 'Initiative': '16', 'Enhancements': {}},
 6: {'Title': 'Grab and Go', 'Initiative': '87', 'Enhancements': {}}, 
 7: {'Title': 'Warding Strength', 'Initiative': '32', 'Enhancements': {}}, 
 8: {'Title': 'Shield Bash', 'Initiative': '15', 'Enhancements': {}}, 
 9: {'Title': 'Leaping Cleave', 'Initiative': '54', 'Enhancements': {}}, 
 10: {'Title': 'Spare Dagger', 'Initiative': '27', 'Enhancements': {}}, 
 11: {'Title': 'Skewer', 'Initiative': '35', 'Enhancements': {}}, 
 12: {'Title': 'Balanced Measure', 'Initiative': '77', 'Enhancements': {}}, 
 13: {'Title': 'Wall of Doom', 'Initiative': '20', 'Enhancements': {}}, 
 14: {'Title': 'Fatal Advance', 'Initiative': '40', 'Enhancements': {}}, 
 15: {'Title': 'Juggernaut', 'Initiative': '34', 'Enhancements': {}}}